name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.47

    - name: Fetch krew manifest
      run: |
        curl -o plugins/download.yaml https://raw.githubusercontent.com/krew-release-bot/krew-index/Anddd7-download-kubectl-download-${{  github.ref_name }}/plugins/download.yaml

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        base: main
        title: Update kubectl-download to ${{ github.ref_name }}
        delete-branch: true
        